version: '3.8'

services:
  # 1. Database PostgreSQL
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_docs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tuongbv.22it@vku.udn.vn  # <--- User đăng nhập>
      PGADMIN_DEFAULT_PASSWORD: buivantuong123          # <--- Pass đăng nh>
    ports:
      - "5050:80" # Map port 80 trong docker ra 5050 của VPS
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:          # <--- THÊM DÒNG NÀY
      - rag_network
   # 2. MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: rag_minio
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      MINIO_ROOT_USER: minio-local-admin
      MINIO_ROOT_PASSWORD: minio-local-password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - rag_network

  # 3. MinIO Client (Tự động tạo Bucket khi khởi động)
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio-local-admin min>
      /usr/bin/mc mb myminio/ai-documents-local;
      /usr/bin/mc anonymous set public myminio/ai-documents-local;
      exit 0;
      "
    networks:
      - rag_network
volumes:
  postgres_data:
  minio_data:
  pgadmin-data:
networks:
  rag_network:
    driver: bridge
